### ISSUE TITLE
Not working after updating to Vert.x 4.3.2 using LogbackConverter with debug level

### ISSUE THREAD

**Issue by runtarinn** [reactiverse/reactiverse-contextual-logging#52]
The LogbackConverter seems to be causing problem when updating to Vert.x 4.3.2  (Is working fine with Vert.x 4.3.1). This only happens when using debug level.

Assuming there is some debug log that is logged before the InternalContext has been initialized.

This is the stacktrace I get when starting a simple starter project:

```
Aug 17, 2022 10:17:03 PM io.vertx.core.impl.launcher.commands.Watcher
INFO: Watched paths: [C:\temp\starter\.\src]
Aug 17, 2022 10:17:03 PM io.vertx.core.impl.launcher.commands.Watcher
INFO: Starting the vert.x application in redeploy mode
Starting vert.x application...
a88d2040-04d5-4a21-9209-86244ada7f81-redeploy
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.impl.VertxImpl
        at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:225)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:114)
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:284)
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:246)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.vertx.core.Launcher.main(Launcher.java:45)
```

This is my logback.xml file
```xml
<configuration debug="false">
<conversionRule conversionWord="mdc"
                  converterClass="io.reactiverse.contextual.logging.LogbackConverter"/>

  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n - %mdc{test:-ble}</pattern>
    </encoder>
  </appender>

  <root level=DEBUG">
    <appender-ref ref="CONSOLE"/>
  </root>
</configuration>
```

**Comment by tsegismont** [comment]
Can you share your small reproducer project on GitHub?

**Comment by runtarinn** [comment]
Sure, here is a reproducer:
https://github.com/runtarinn/reactiverse-contextual-logging-reproducer

Not sure if this is an error in this library or in vertx-core. I tried to add try/catch block inside the "convert" method and print out the stacktrace. 

```
  @Override
  public String convert(ILoggingEvent event) {
	  try{
    ContextInternal context = (ContextInternal) Vertx.currentContext();
    if (context != null && key != null) {
      return ContextualData.getOrDefault(key, defaultValue);
    }
    return defaultValue;
	  }catch(Throwable e)
	  {
            e.printStackTrace();
            throw e;
	  }
  }
```

This is what I got:

```
java.lang.ExceptionInInitializerError
        at io.vertx.core.impl.ContextInternal.current(ContextInternal.java:46)
        at io.vertx.core.Vertx.currentContext(Vertx.java:116)
        at io.reactiverse.contextual.logging.LogbackConverter.convert(LogbackConverter.java:58)
        at io.reactiverse.contextual.logging.LogbackConverter.convert(LogbackConverter.java:30)
        at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
        at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:115)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:165)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
        at ch.qos.logback.core.encoder.LayoutWrappingEncoder.encode(LayoutWrappingEncoder.java:116)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.log(Logger.java:765)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:188)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:160)
        at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:156)
        at io.vertx.core.logging.SLF4JLogDelegate.debug(SLF4JLogDelegate.java:122)
        at io.vertx.core.logging.LoggerFactory.configureWith(LoggerFactory.java:66)
        at io.vertx.core.logging.LoggerFactory.initialise(LoggerFactory.java:49)
        at io.vertx.core.logging.LoggerFactory.<clinit>(LoggerFactory.java:34)
        at io.vertx.core.impl.logging.LoggerFactory.getLogger(LoggerFactory.java:26)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.<init>(ClasspathHandler.java:46)
        at io.vertx.core.impl.launcher.commands.RunCommand.<init>(RunCommand.java:36)
        at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:60)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:179)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:234)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.vertx.core.Launcher.main(Launcher.java:45)
Caused by: java.lang.NullPointerException
        at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:93)
        at io.vertx.core.logging.LoggerFactory.getLogger(LoggerFactory.java:82)
        at io.vertx.core.impl.logging.LoggerFactory.getLogger(LoggerFactory.java:26)
        at io.vertx.core.impl.VertxImpl.<clinit>(VertxImpl.java:90)
        ... 35 more
```

**Comment by tsegismont** [comment]
This happens after a change in Vert.x core `ContextInternal` implementation.

I will update Vert.x core so that nothing is logged until `LoggerFactory` is initialized.

As a workaround, you may add `<logger name="io.vertx.core.logging.LoggerFactory" level="INFO"/>` to your logger configuration.

**Comment by runtarinn** [comment]
Thank you very much for quick response and the workaround.
